title: Andrzej Pichliński
logo: /assets/img/avatar.jpg
description: My Digital CV with GitHub Pages.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

hackerrank:
  is_user_page: true
  owner_url: https://www.hackerrank.com/profile/andrzej_pichlin1
github:
  is_user_page: true
  owner_url: https://github.com/apichlinski
linkedin:
  is_user_page: true
  owner_url: https://www.linkedin.com/in/andrzej-pichli%C5%84ski-667807100/
credly:
  is_user_page: true
  owner_url: https://www.credly.com/users/andrzej-pichlinski/badges
